notifications:
  email: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    -
    - DEPENDENCIES=--prefer-lowest

matrix:
  fast_finish: true

cache:
  directories:
    - vendor

install:
  - composer validate
  - composer update $DEPENDENCIES

script:
  - XDEBUG_MODE=coverage composer test -- --coverage-clover=build/logs/clover.xml

after_success:
  - composer require satooshi/php-coveralls
  - vendor/bin/coveralls -v
